// Built-in games. `key` is the stable identifier clients send when picking
// presets; emoji + color drive the game tile look everywhere in the UI.
module.exports = [
  {
    key: 'openguessr',
    category: 'geo',
    name: 'OpenGuessr',
    site: 'https://openguessr.com/',
    hint: 'Create a party and copy the invite link.',
    emoji: '🌍',
    color: '#2e7dd7',
  },
  {
    key: 'codenames',
    category: 'deduction',
    name: 'Code Names',
    site: 'https://codenames.game/',
    hint: 'Create room → copy the room URL from the address bar.',
    emoji: '🕵️',
    color: '#c0392b',
  },
  {
    key: 'wikispeedruns',
    category: 'wiki',
    variantGroup: 'wikirace',
    defaultOn: false,
    name: 'WikiSpeedruns',
    site: 'https://wikispeedruns.com/',
    hint: 'Create a private lobby and copy the invite link.',
    emoji: '📚',
    color: '#7d3fbf',
  },
  {
    key: 'dobyvatel',
    category: 'geo',
    name: 'Dobyvatel',
    site: 'https://www.dobyvatel.cz/',
    hint: 'Create a quick game and copy the invite link.',
    emoji: '⚔️',
    color: '#c98a1b',
  },
  {
    key: 'skribbl',
    category: 'drawing',
    variantGroup: 'drawing',
    name: 'Skribbl',
    site: 'https://skribbl.io/',
    hint: 'Create a private room and copy the invite link.',
    emoji: '🎨',
    color: '#16897a',
  },
  {
    key: 'garticphone',
    category: 'drawing',
    variantGroup: 'drawing',
    defaultOn: false,
    name: 'Gartic Phone',
    site: 'https://garticphone.com/',
    hint: 'Start a room and copy the invite link.',
    emoji: '📞',
    color: '#b13b73',
  },
  {
    key: 'bombparty',
    category: 'action',
    name: 'BombParty',
    site: 'https://jklm.fun/',
    hint: 'Start a room and share the room link.',
    emoji: '💣',
    color: '#d9480f',
  },
  {
    key: 'haxball',
    category: 'action',
    name: 'Haxball',
    site: 'https://www.haxball.com/',
    hint: 'Create a room and copy the room link.',
    emoji: '⚽',
    color: '#2f9e44',
  },
  {
    key: 'curvefever',
    category: 'action',
    name: 'Curve Fever',
    site: 'https://curvefever.pro/',
    hint: 'Create a custom room and share the link.',
    emoji: '🐍',
    color: '#0b7285',
  },
  {
    key: 'colonist',
    category: 'strategy',
    name: 'Colonist',
    site: 'https://colonist.io/',
    hint: 'Create a private room and share the room link.',
    emoji: '🌾',
    color: '#a87c4f',
  },
  {
    key: 'spyfall',
    category: 'deduction',
    name: 'Spyfall',
    site: 'https://spyfall.app/',
    hint: 'Create a game and share the join link.',
    emoji: '🔍',
    color: '#4a4e69',
  },
  {
    key: 'smashkarts',
    category: 'action',
    name: 'Smash Karts',
    site: 'https://smashkarts.io/',
    hint: 'Create a private room and share the room link.',
    emoji: '🏎️',
    color: '#9c36b5',
  },
  {
    key: 'wikirace',
    category: 'wiki',
    variantGroup: 'wikirace',
    name: 'WikiRace',
    site: 'https://www.wikirace.app/',
    hint: 'Create a lobby and share the lobby code or link.',
    emoji: '🏃',
    color: '#5c940d',
  },
  {
    key: 'typeracer',
    category: 'action',
    name: 'TypeRacer',
    site: 'https://play.typeracer.com/',
    hint: "Click 'Race your friends' and share the track link.",
    emoji: '⌨️',
    color: '#364fc7',
  },
];
